//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pidelo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pidelodbEntities1 : DbContext
    {
        public pidelodbEntities1()
            : base("name=pidelodbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCliente> tblClientes { get; set; }
        public virtual DbSet<tblTipoDocumento> tblTipoDocumentoes { get; set; }
        public virtual DbSet<tblUsuario> tblUsuarios { get; set; }
        public virtual DbSet<tblZona> tblZonas { get; set; }
    }
}
