//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pidelo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCliente
    {
        public int idCliente { get; set; }
        public string razonSocial { get; set; }
        public string nombreComercial { get; set; }
        public int idTipoDocumento { get; set; }
        public string documento { get; set; }
    
        public virtual tblTipoDocumento tblTipoDocumento { get; set; }
    }
}
