//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pidelo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTipoDocumento
    {
        public tblTipoDocumento()
        {
            this.tblClientes = new HashSet<tblCliente>();
        }
    
        public int idTipoDocumento { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<tblCliente> tblClientes { get; set; }
    }
}
